### ISSUE TITLE
Compile error _kReachabilityChangedNotification

### ISSUE THREAD

**Issue by dav91** [teads/TeadsSDK-iOS#23]
I upgraded the framework to version 1.6.2, now I can't compile my application because of a duplicate symbol *_kReachabilityChangedNotification*. That's because I use the **Reachability framework** in my projects. TeadsSDK 1.6.0 works fine.

This is the error I get:

> duplicate symbol _kReachabilityChangedNotification in:
>     /Users/davidebalistreri/Library/Developer/Xcode/DerivedData/Calcio_Dilettanti-froqtebyowrsgqemhxwqpdubdgeh/Build/Products/Debug-iphoneos/libReachability.a(Reachability.o)
>     /Users/davidebalistreri/Desktop/Calcio Dilettanti/iOS/Calcio Dilettanti/TeadsSDK.framework/TeadsSDK(TeadsReachability.o)
> ld: 1 duplicate symbol for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thank you for your support!

**Comment by ibrahimennafaa** [comment]
Hi,

This issue is fixed in the next 1.6.3 release (ETA end of week).

Thanks for reporting

**Comment by dav91** [comment]
Hi, unfortunately this issue is still present in version 1.6.4.

Here's the full error log:
> Ld /Users/davidebalistreri/Library/Developer/Xcode/DerivedData/Calcio_Dilettanti-froqtebyowrsgqemhxwqpdubdgeh/Build/Products/Debug-iphoneos/Calcio\ Dilettanti.app/Calcio\ Dilettanti normal arm64
    cd "/Users/davidebalistreri/Desktop/Calcio Dilettanti/iOS/Calcio Dilettanti"
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -L/Users/davidebalistreri/Library/Developer/Xcode/DerivedData/Calcio_Dilettanti-froqtebyowrsgqemhxwqpdubdgeh/Build/Products/Debug-iphoneos -L/Users/davidebalistreri/Desktop/Calcio\ Dilettanti/iOS/Calcio\ Dilettanti/Pods/Flurry-iOS-SDK/Flurry -L/Users/davidebalistreri/Desktop/Calcio\ Dilettanti/iOS/Calcio\ Dilettanti/Pods/GoogleAnalytics/Libraries -F/Users/davidebalistreri/Library/Developer/Xcode/DerivedData/Calcio_Dilettanti-froqtebyowrsgqemhxwqpdubdgeh/Build/Products/Debug-iphoneos -F/Users/davidebalistreri/Desktop/Calcio\ Dilettanti/iOS/Calcio\ Dilettanti/Pods/GoogleMobileAds/Frameworks -F/Users/davidebalistreri/Desktop/Calcio\ Dilettanti/iOS/Calcio\ Dilettanti -filelist /Users/davidebalistreri/Library/Developer/Xcode/DerivedData/Calcio_Dilettanti-froqtebyowrsgqemhxwqpdubdgeh/Build/Intermediates/Calcio\ Dilettanti.build/Debug-iphoneos/Calcio\ Dilettanti.build/Objects-normal/arm64/Calcio\ Dilettanti.LinkFileList -Xlinker -rpath -Xlinker /Users/davidebalistreri/Desktop/Calcio\ Dilettanti/iOS/Calcio\ Dilettanti -miphoneos-version-min=7.0 -dead_strip -ObjC -lAFNetworking -lBolts -lDBToolkit -lFBSDKCoreKit -lFBSDKLoginKit -lFBSDKShareKit -lFlurry-iOS-SDK -lFlurry_7.3.0 -lGoogleAnalytics -lMBProgressHUD -lReachability -lTHCircularProgressView -lsqlite3 -lz -framework CoreData -framework CoreGraphics -framework Foundation -framework GoogleMobileAds -framework MobileCoreServices -framework Security -framework SystemConfiguration -framework UIKit -weak_framework Accounts -weak_framework AudioToolbox -weak_framework CoreGraphics -weak_framework CoreLocation -weak_framework Foundation -weak_framework QuartzCore -weak_framework Security -weak_framework Social -weak_framework UIKit -fobjc-arc -fobjc-link-runtime -lxml2 -lsqlite3.0 -framework Crashlytics -framework TeadsSDK -lPods-Calcio\ Dilettanti -Xlinker -dependency_info -Xlinker /Users/davidebalistreri/Library/Developer/Xcode/DerivedData/Calcio_Dilettanti-froqtebyowrsgqemhxwqpdubdgeh/Build/Intermediates/Calcio\ Dilettanti.build/Debug-iphoneos/Calcio\ Dilettanti.build/Objects-normal/arm64/Calcio\ Dilettanti_dependency_info.dat -o /Users/davidebalistreri/Library/Developer/Xcode/DerivedData/Calcio_Dilettanti-froqtebyowrsgqemhxwqpdubdgeh/Build/Products/Debug-iphoneos/Calcio\ Dilettanti.app/Calcio\ Dilettanti
> 
> duplicate symbol _kReachabilityChangedNotification in:
    /Users/davidebalistreri/Library/Developer/Xcode/DerivedData/Calcio_Dilettanti-froqtebyowrsgqemhxwqpdubdgeh/Build/Products/Debug-iphoneos/libReachability.a(Reachability.o)
    /Users/davidebalistreri/Desktop/Calcio Dilettanti/iOS/Calcio Dilettanti/TeadsSDK.framework/TeadsSDK(TeadsReachability.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Niko-r** [comment]
Hello @dav91 ,

This issue is fixed for good in the next v1.6.5 release (ETA end of week).

Thanks for reporting

**Comment by Niko-r** [comment]
Hello @dav91, this has been fixed

**Comment by Niko-r** [comment]
Hello @dav91 , 

Fix is present in v1.6.6 https://github.com/teads/TeadsSDK-iOS/releases/tag/v1.6.6

Let me know if everything is ok for you, so we can close this issue.

Thank you

**Comment by dav91** [comment]
Issue is fixed, thank you for your kind support.
